#!/usr/bin/env bash
set -euo pipefail

# Seeds guard and worker workspaces from core/guard and core/worker.
#
# What gets seeded (per profile):
#   - Identity:  IDENTITY.md (Op / Chloe)
#   - Role:      ROLE.md (and any other core/<profile>/*.md)
#   - Skills:    core/<profile>/skills/ -> workspace/skills/
#
# Run manually after git pull (e.g. via setup step 14 or ./scripts/sync-workspaces.sh).
#
# Optional: sync only one profile.
#   SYNC_PROFILE=worker ./sync-workspaces.sh   OR   ./sync-workspaces.sh --profile worker
SYNC_PROFILE="${SYNC_PROFILE:-}"

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
STACK_DIR=$(cd "$SCRIPT_DIR/../.." && pwd)

WORKER_WS=${OPENCLAW_WORKSPACE_DIR:-${WORKER_WORKSPACE_DIR:-/var/lib/openclaw/chloe/workspace}}
GUARD_WS=${OPENCLAW_GUARD_WORKSPACE_DIR:-${GUARD_WORKSPACE_DIR:-/var/lib/openclaw/guard/workspace}}

# Display names for identity substitution (set in stack.env)
export GUARD_DISPLAY_NAME=${GUARD_DISPLAY_NAME:-Op}
export WORKER_DISPLAY_NAME=${WORKER_DISPLAY_NAME:-Chloe}

for arg in "$@"; do
  case "$arg" in
    --profile=*) SYNC_PROFILE="${arg#--profile=}" ;;
    --profile)   : ;; # next arg will be consumed below if needed
  esac
done
[ "${1:-}" = "--profile" ] && [ -n "${2:-}" ] && SYNC_PROFILE="$2"

sync_one() {
  local profile="$1" ws="$2"
  local core_dir="$STACK_DIR/core/$profile"

  [ -d "$core_dir" ] || return 0
  mkdir -p "$ws"

  shopt -s nullglob
  local f
  for f in "$core_dir"/*.md; do
    local name target tmp
    name=$(basename "$f")
    target="$ws/$name"
    tmp=$(mktemp)

    python3 - "$f" "$target" "$profile" <<'PY' > "$tmp"
import pathlib, re, sys
core_path=pathlib.Path(sys.argv[1])
target_path=pathlib.Path(sys.argv[2])
profile=sys.argv[3]

core=core_path.read_text() if core_path.exists() else ''
# Substitute {{ENV_VAR}} placeholders with values from environment
import os
core=re.sub(r'\{\{(\w+)\}\}', lambda m: os.environ.get(m.group(1), m.group(0)), core)

begin_core='<!-- CORE:BEGIN -->'
end_core='<!-- CORE:END -->'
begin_local='<!-- LOCAL:BEGIN -->'
end_local='<!-- LOCAL:END -->'

header=(
  '<!-- GENERATED by scripts/sync-workspaces.sh -->\n'
  f'<!-- profile={profile} source={core_path.as_posix()} -->\n\n'
)

def compose(local_text:str)->str:
    return (
        header +
        f'{begin_core}\n{core.rstrip()}\n{end_core}\n\n'
        f'{begin_local}\n{local_text.rstrip()}\n{end_local}\n'
    )

if not target_path.exists():
    print(compose(f'# Local layer for {target_path.name}\n\n(put your local, instance-specific instructions here)'))
    raise SystemExit(0)

existing=target_path.read_text()

core_re=re.compile(r'<!-- CORE:BEGIN -->.*?<!-- CORE:END -->', re.S)
local_re=re.compile(r'<!-- LOCAL:BEGIN -->(.*?)<!-- LOCAL:END -->', re.S)

if core_re.search(existing) and local_re.search(existing):
    local_body=local_re.search(existing).group(1).strip('\n')
    print(compose(local_body))
else:
    # Migrate legacy file: preserve entire current file as local layer.
    print(compose(existing.strip('\n')))
PY

    install -m 0644 "$tmp" "$target"
    rm -f "$tmp"
  done

  shopt -u nullglob

  # Sync skills subtree if present (core/<profile>/skills/ -> workspace/skills/)
  local skills_src="$core_dir/skills"
  if [ -d "$skills_src" ]; then
    mkdir -p "$ws/skills"
    rsync -a --delete "$skills_src/" "$ws/skills/" 2>/dev/null || cp -R "$skills_src"/* "$ws/skills/" 2>/dev/null || true
  fi

  # Store hash of core/<profile> so setup can show ✅ Seeded only when workspace matches repo
  python3 "$STACK_DIR/scripts/host/seed-hash.py" set "$STACK_DIR" "$profile" "$ws"
}

if [ -z "$SYNC_PROFILE" ]; then
  sync_one worker "$WORKER_WS"
  sync_one guard "$GUARD_WS"
  chown -R 1000:1000 "$WORKER_WS" "$GUARD_WS" 2>/dev/null || true
  echo "[sync] workspaces refreshed from core profiles"
else
  case "$SYNC_PROFILE" in
    worker) sync_one worker "$WORKER_WS"; chown -R 1000:1000 "$WORKER_WS" 2>/dev/null || true; echo "[sync] worker workspace refreshed from core/worker" ;;
    guard)  sync_one guard  "$GUARD_WS";  chown -R 1000:1000 "$GUARD_WS"  2>/dev/null || true; echo "[sync] guard workspace refreshed from core/guard" ;;
    *) echo "[sync] unknown SYNC_PROFILE=$SYNC_PROFILE (use worker or guard)" >&2; exit 1 ;;
  esac
fi
